fix: If ntpdate is not found during testing, install it.
This is required for the tests to pass on the github action runners.

diff --git a/metadata/metadata b/metadata/metadata
--- a/metadata/metadata
+++ b/metadata/metadata
@@ -44,6 +44,12 @@ test_start_container() {
 test_image_after_container_startup() {
     local container_name="${1:?}"
 
+    if ! hash foo 2>/dev/null; then
+        echo "ntpdate not found, installing ..."
+        sudo DEBIAN_FRONTEND=noninteractive apt-get update
+        sudo DEBIAN_FRONTEND=noninteractive apt-get install -qq ntpdate
+    fi
+
     echo "Verifying ntp using ntpdate"
     ntpdate -q "$(container_ip "${container_name:?}")"
 }
